services:
  # Servicio para la aplicación backend
  backend:
    image: chocoprisky14/backendinmo:1.0
    env_file:
      - .env
    ports:
      - "3000:3000" # Expone el puerto 3000 del contenedor al puerto 3000 del host
    depends_on:
      - mongodb # Asegura que MongoDB se inicie antes que el backend
    networks:
      - app-network

  # Servicio para la aplicación frontend (Angular)
  backofice:
    image: chocoprisky14/backofficeinmo:1.0
    build:
      context: ./frontend # Ruta relativa donde se encuentra el Dockerfile del frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Expone el puerto 80 del contenedor al puerto 4200 del host
    depends_on:
      - backend # Asegura que el backend se inicie antes que el frontend
    networks:
      - app-network

  # Servicio para MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expone el puerto 27017 de MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Usuario administrador
      - MONGO_INITDB_ROOT_PASSWORD=example # Contraseña del usuario administrador
    volumes:
      - mongodb_data:/data/db # Guarda los datos en un volumen persistente
    networks:
      - app-network

# Volúmenes para mantener las datos de MongoDB
volumes:
  mongodb_data:

# Red compartida entre los servicios
networks:
  app-network:
    driver: bridge
