version: '3.8'

services:
  # Servei per a l'aplicació backend
  backend:
    image: chocoprisky14/backendinmo:1.0
    env_file:
      - .env
    ports:
      - "3000:3000" # Exposa el port 3000 del contenidor al port 3000 de l'host
    depends_on:
      - mongodb # S'assegura que MongoDB s'inicia abans que el backend

   # Servicio para la aplicación frontend (Angular)
  backofice:
    image: chocoprisky14/backoficeinmo:1.0
    build:
      context: ./frontend # Ruta relativa donde se encuentra el Dockerfile del frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Expone el puerto 80 del contenedor al puerto 4200 del host
    depends_on:
      - backend # Asegura que el backend se inicie antes que el frontend
    networks:
      - app-network

  # Servei per a MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Exposa el port 27017 de MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Usuari administrador
      - MONGO_INITDB_ROOT_PASSWORD=example # Contrasenya de l'usuari administrador
    volumes:
      - mongodb_data:/data/db # Guarda les dades en un volum persistent

# Volums per mantenir les dades de MongoDB
volumes:
  mongodb_data: